# -*- coding: utf-8 -*-
"""Canonical fact sheet from the frozen coding table (n = 67).

Writes corpus/FACT_SHEET.md. Rule (CLAUDE.md cross-check workflow): thesis prose
may only cite corpus numbers that appear here; verification = diff against this file.
Groupings mirror corpus/make_figures.py exactly.
"""
import csv
import collections
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
with open(ROOT / "coding_table.csv", encoding="utf-8-sig") as f:
    ROWS = list(csv.DictReader(f, delimiter=";"))
assert len(ROWS) == 67 and all(r["coding_status"] == "final" for r in ROWS)

N = len(ROWS)
out = ["# Fact Sheet — coding table (n = 67, all rows final)", "",
       "Generated by corpus/fact_sheet.py. Do not edit; re-run instead.", ""]


def pct(k):
    return f"{k}/{N} = {100 * k / N:.1f}%"


def section(title, counter, note=None):
    out.append(f"## {title}")
    if note:
        out.append(f"({note})")
    for key, c in counter.most_common():
        out.append(f"- {key}: {c} ({100 * c / N:.1f}%)")
    out.append("")


# year
years = collections.Counter(r["year"] for r in ROWS)
out.append("## Publication year")
for y in sorted(years):
    out.append(f"- {y}: {years[y]}")
recent = years["2025"] + years["2026"]
out.append(f"- 2025+2026 combined: {pct(recent)} (two thirds)")
out.append(f"- earliest included study: {min(years)}")
out.append("")

# journals
journals = collections.Counter(r["journal"] for r in ROWS)
out.append("## Journals")
out.append(f"- distinct journals: {len(journals)}")
for j, c in journals.most_common(8):
    out.append(f"- {j}: {c}")
out.append("")

section("AJG 2024 rating", collections.Counter(r["ajg2024"] for r in ROWS))
out.append(f"- AJG 4 or 4* combined: {collections.Counter(r['ajg2024'] for r in ROWS)['4'] + collections.Counter(r['ajg2024'] for r in ROWS)['4*']}")
out.append("")

section("Method", collections.Counter(r["method"] for r in ROWS))


# AI measurement families (mirrors grouping logic agreed for the prose)
def measure_family(m):
    m = m.lower()
    if m.startswith("survey"):
        return "survey construct / self-report"
    if "case" in m or "interview" in m:
        return "case / qualitative observation"
    if "announce" in m:
        return "archival: announcements"
    if "patent" in m:
        return "archival: patents"
    if any(k in m for k in ("job posting", "human capital", "labor-based", "workforce", "resume", "ai-skilled")):
        return "archival: AI workforce measures"
    if "10-k" in m or "text" in m or "keyword" in m:
        return "archival: disclosure text mining"
    return "archival: other single-study instrument"


fam = collections.Counter(measure_family(r["ai_measure"]) for r in ROWS)
section("AI measurement family", fam)
survey = fam["survey construct / self-report"]
qual = fam["case / qualitative observation"]
out.append(f"- survey vs archival vs qualitative: {survey} / {N - survey - qual} / {qual}")
out.append("")


# geography (mirrors make_figures.region)
def region(raw):
    r = raw.lower()
    if r.startswith("multi") or "asia-pacific" in r or "china + europe" in r:
        return "Multi-country"
    if r in ("eu", "europe") or r.startswith(("eu (", "europe (")):
        return "Europe (multi-country)"
    return raw.split(" (")[0]


geo = collections.Counter(region(r["country_region"]) for r in ROWS)
section("Sample geography (normalized)", geo)
eur_single = sum(c for k, c in geo.items() if k in ("Italy", "UK", "Germany", "France"))
out.append(f"- USA+China combined: {pct(geo['USA'] + geo['China'])}")
out.append(f"- European samples total (multi-country + Italy/UK/Germany/France): {geo['Europe (multi-country)'] + eur_single}")
out.append("")

# industry
ind = collections.Counter(r["industry"] for r in ROWS)
cross = sum(c for k, c in ind.items() if k.startswith("cross-industry"))
manuf = sum(c for k, c in ind.items() if k.startswith("manufacturing"))
out.append("## Industry")
out.append(f"- cross-industry (all variants): {cross}")
out.append(f"- manufacturing (all variants): {manuf}")
out.append(f"- other single settings: {N - cross - manuf}")
out.append("")

# outcomes and directions
oc = collections.Counter(r["outcome_construct"] for r in ROWS)
section("Outcome construct", oc)
out.append(f"- studies measuring CA at all (competitive_advantage + both): {pct(oc['competitive_advantage'] + oc['both'])}")
out.append("")
section("Effect direction", collections.Counter(r["effect_direction"] for r in ROWS))

out.append("## Outcome construct x effect direction")
cross_tab = collections.Counter((r["outcome_construct"], r["effect_direction"]) for r in ROWS)
for (o, d), c in sorted(cross_tab.items()):
    out.append(f"- {o} x {d}: {c}")
ca_rows = [r for r in ROWS if r["outcome_construct"] in ("competitive_advantage", "both")]
ca_dir = collections.Counter(r["effect_direction"] for r in ca_rows)
out.append(f"- within CA-measuring studies ({len(ca_rows)}): " + ", ".join(f"{k} {v}" for k, v in ca_dir.most_common()))
out.append("")

# conditions
with_cond = sum(1 for r in ROWS if r["conditions"].strip())
out.append("## Conditions")
out.append(f"- studies with at least one identified condition: {pct(with_cond)}")
out.append(f"- studies with unconditional evidence (empty conditions): {N - with_cond}")
out.append("")

# condition clusters for section 4.2 — source: conditions_clusters.md (frozen by
# the author 13 Aug 2026), parsed from the per-study detail table and validated
# against the coding table so outline and detail can never drift apart again.
CLUSTER_TITLES = {
    "4.2.1": "Complementary investments and resources",
    "4.2.2": "Organizational capabilities and human capital as the channel",
    "4.2.3": "Leadership, governance, and management",
    "4.2.4": "Firm characteristics and market position",
    "4.2.5": "Environmental conditions",
    "4.2.6": "Dose, credibility, and timing",
}
clusters: dict[str, list[str]] = {k: [] for k in CLUSTER_TITLES}
assigned: set[str] = set()
md = (ROOT / "conditions_clusters.md").read_text(encoding="utf-8")
detail = md.split("## Zuordnung je Studie", 1)[1]
for m in re.finditer(r"^\| (S\d\d) \| ([^|]+) \|", detail, re.M):
    sid, cell = m.group(1), m.group(2)
    assigned.add(sid)
    for c in re.findall(r"4\.2\.\d", cell):
        clusters[c].append(sid)

ids_with_cond = {r["study_id"] for r in ROWS if r["conditions"].strip()}
assert assigned == ids_with_cond, sorted(assigned ^ ids_with_cond)
out.append("## Condition clusters (section 4.2 structure, frozen 13 Aug 2026)")
out.append("(one study can appear in several clusters; source: corpus/conditions_clusters.md)")
for c, title in CLUSTER_TITLES.items():
    out.append(f"- {c} {title}: {len(clusters[c])}")
out.append(f"- assignments total: {sum(len(v) for v in clusters.values())} across {len(assigned)} studies")
out.append(f"- unconditional contrast group: {', '.join(sorted(ids_with_cond ^ {r['study_id'] for r in ROWS}))}")
out.append("")

(ROOT / "FACT_SHEET.md").write_text("\n".join(out), encoding="utf-8")
print("wrote", ROOT / "FACT_SHEET.md")
for c, title in CLUSTER_TITLES.items():
    print(c, f"(n={len(clusters[c])}):", " ".join(sorted(clusters[c])))
